Changed implementation function_ref back to master, added prefix OMP to the ones that used OpenMP. Copyied those and changed to ACC. All calls were changed.
CGOpenMPRuntime and CGOpenACCRuntime used to conflict because they added
duplicates. Since we cannot just delete one of them, we created a
"common ground file" CGOpenRuntime, that implements what was duplicate.
Both CGOpenMPRuntime and CGOpenACCRuntime include that file

Compilation error: compiler can't find file CGOpenRuntime.h